interval: 180
# account_policy: random
account_policy: round_robin
commit_branch: master
pr_branch: dev
limit: 10
gitee:
  - name: 蔡宇昕
    gitee_name: caiyuxin
    email: caiyuxin@kylinos.cn
    password: "qwer1234"
    token: "f19f4ebc63047f3c2ef79e505a501a91"
  - name: 李秋雨
    gitee_name: liqiuyu123
    email: liqiuyu@kylinos.cn
    password: "Liqiuyu123"
    token: "0648974156178c693c3bf7570c651e5f"
  - name: 蔡宇昕
    gitee_name: caiyuxin
    email: caiyuxin@kylinos.cn
    password: "qwer1234"
    token: "f19f4ebc63047f3c2ef79e505a501a91"
  - name: 蔡宇昕
    gitee_name: caiyuxin
    email: caiyuxin@kylinos.cn
    password: "qwer1234"
    token: "f19f4ebc63047f3c2ef79e505a501a91"
  - name: 李秋雨
    gitee_name: liqiuyu123
    email: liqiuyu@kylinos.cn
    password: "Liqiuyu123"
    token: "0648974156178c693c3bf7570c651e5f"
